[package]
name = "inserter-x"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = "0.1.13"
arrow = { version = "55.1.0", features = ["ffi"], default-features = false }
ctrlc = "3.4.7"
polars = { version = "0.48.1", features = ["csv", "lazy", "fmt"], default-features = false }
polars-arrow = "0.48.1"
postgres = "0.19.10"
rand = "0.9.1"
sqlx = { version = "0.8.6", features = ["macros", "postgres", "runtime-tokio"] }
tokio = "1.45.1"

